spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit
  datasource:
    url: jdbc:postgresql://localhost:5432/pingwise
    username: postgres
    password: postgres
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

rabbit:
  check:
    exchange: "checks.exchange"
    queue: "checks.queue"
    dead_queue: "checks.dead.queue"
    dead_exchange: "checks.dlx"
    dead_routing: "checks.read"