spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit
  datasource:
    url: jdbc:postgresql://localhost:5432/pingwise
    username: postgres
    password: postgres
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

rabbit:
  check:
    queue: pingwise.check.queue
    exchange: pingwise.check.exchange
    routing: pingwise.check.routing
    dead_queue: pingwise.check.dead.queue
    dead_exchange: pingwise.check.dead.exchange
    dead_routing: pingwise.check.dead.routing

  monitor:
    update:
      queue: pingwise.monitor.update.queue
      exchange: pingwise.monitor.update.exchange
      routing: pingwise.monitor.update.routing
      dead_queue: pingwise.monitor.update.dead.queue
      dead_exchange: pingwise.monitor.update.dead.exchange
      dead_routing: pingwise.monitor.update.dead.routing